# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Button - DevOps Advocate
email: will@willbutton.co
description: > # this means to ignore newlines until "baseurl:"
  The official blog and website of Will Button.
  DevOps Engineer | Egghead.io | Pluralsight | Speaker
  Scalability | Performance | WTF Inspector
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://willbutton.co" # the base hostname & protocol for your site
twitter_username: wfbutton
github_username:  rekibnikufesin

# Build settings
markdown: kramdown

# Github pages gems
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed
